<%!
from alembic import op
import sqlalchemy as sa
%>

-- commands auto generated by Alembic - please adjust! --

<% if 'revision' in context: %>
revision = '<%= revision %>'
<% else: %>
revision = None
<% endif %>

<% if 'down_revision' in context: %>
down_revision = '<%= down_revision %>'
<% else: %>
down_revision = None
<% endif %>

<% if 'branch_labels' in context: %>
branch_labels = <%= repr(branch_labels) %>
<% else: %>
branch_labels = None
<% endif %>

<% if 'depends_on' in context: %>
depends_on = <%= repr(depends_on) %>
<% else: %>
depends_on = None
<% endif %>

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###